### ISSUE TITLE
Feature request: strip if value undefined

### ISSUE THREAD

**Issue by Roam-Cooper** [gillesruppert/node-interpolate#1]
Hey, can I request a feature?

A boolean option in the config where the delimiter is passed that allows us to strip out the delimiter even if the value is null/undefined.

We'd rather have blanks in the text if something fails rather than `{nastyDelimiter} abcd {anotherDelimiter}`

**Comment by gillesruppert** [comment]
Hi @Roam-Cooper,
I'm not too keen on adding support for this. You could easily achieve this by using the default operator, i.e.

```
const interpolationValue = nullableValue || '';
```

or similar for areas where you are concerned. If you want to do this automatically, you could also write a wrapper around node-interpolate which takes care of this for values that are `null` or `undefined`.

If you're using Babel, you might also consider using the new template literals that are in ES6. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

I hope this helps. Let me know if you have any questions.
