### ISSUE TITLE
not working with ${}

### ISSUE THREAD

**Issue by suiteappdev** [gillesruppert/node-interpolate#2]
not working with ${}

`var interpolate = require('interpolate');
var result = interpolate('hello, ${user}', {
  user: 'armitage'
}, { delimiter: '${}' });`

**Comment by gillesruppert** [comment]
@suiteappdev this won't work. The delimiter needs to be symetrical, i.e. same number of open and close tags (i.e. `${}$` would work).

If you submit a PR with tests, I can consider pulling this in, but I haven't been using this in a while, so not actively maintaining it.
